# Generated by Django 6.0.7 on 2026-08-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='brand',
        ),
    ]
